// Re-export for use in evaluator.
pub use super::expressions::RegexLiteral;

// Object constructor, represented by tuples of (key, value)
pub type Object = Vec<(Ast, Ast)>;

// Sort terms, representend by expresions and a bool indicating descending/ascending
pub type SortTerms = Vec<(Ast, bool)>;

#[derive(Debug, Clone)]
pub enum UnaryOp {
    Minus(Box<Ast>),
    ArrayConstructor(Vec<Ast>),
    ObjectConstructor(Object),
}

#[derive(Debug, PartialEq, Clone)]
pub enum BinaryOp {
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulus,
    Equal,
    NotEqual,
    LessThan,
    GreaterThan,
    LessThanEqual,
    GreaterThanEqual,
    Concat,
    And,
    Or,
    In,
    Map,
    Range,
    FocusBind,
    IndexBind,
    Predicate,
    Apply,
    Bind,
}

impl std::fmt::Display for BinaryOp {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match *self {
            BinaryOp::Add => "+",
            BinaryOp::Subtract => "-",
            BinaryOp::Multiply => "*",
            BinaryOp::Divide => "/",
            BinaryOp::Modulus => "%",
            BinaryOp::Equal => "=",
            BinaryOp::NotEqual => "!=",
            BinaryOp::LessThan => "<",
            BinaryOp::GreaterThan => ">",
            BinaryOp::LessThanEqual => "<=",
            BinaryOp::GreaterThanEqual => ">=",
            BinaryOp::Concat => "&",
            BinaryOp::And => "and",
            BinaryOp::Or => "or",
            BinaryOp::In => "in",
            BinaryOp::Map => ".",
            BinaryOp::Range => "..",
            BinaryOp::FocusBind => "@",
            BinaryOp::IndexBind => "#",
            BinaryOp::Predicate => "[]",
            BinaryOp::Apply => "~>",
            BinaryOp::Bind => ":=",
        })
    }
}

#[derive(Debug, Clone)]
pub enum AstKind {
    Empty,
    Null,
    Bool(bool),
    String(String),
    Number(f64),
    Regex(Box<RegexLiteral>),
    Name(String),
    Var(String),
    Unary(UnaryOp),
    Binary(BinaryOp, Box<Ast>, Box<Ast>),
    GroupBy(Box<Ast>, Object),
    OrderBy(Box<Ast>, Vec<(Ast, bool)>),
    Block(Vec<Ast>),
    Wildcard,
    Descendent,
    Parent,
    Function {
        name: String,
        proc: Box<Ast>,
        args: Vec<Ast>,
        is_partial: bool,
    },
    PartialArg,
    Lambda {
        name: String,
        args: Vec<Ast>,
        body: Box<Ast>,
        thunk: bool,
    },
    Ternary {
        cond: Box<Ast>,
        truthy: Box<Ast>,
        falsy: Option<Box<Ast>>,
    },
    Transform {
        pattern: Box<Ast>,
        update: Box<Ast>,
        delete: Option<Box<Ast>>,
    },

    // Generated by AST post-processing
    Path(Vec<Ast>),
    Filter(Box<Ast>),
    Sort(SortTerms),
    Index(String),
}

/// Rarely-populated decoration fields, boxed to reduce the size of `Ast` on the stack.
#[derive(Debug, Clone, Default)]
pub struct AstExtras {
    /// An optional group by expression, represented as an object.
    pub group_by: Option<(usize, Object)>,

    /// An optional list of predicates.
    pub predicates: Option<Vec<Ast>>,

    /// An optional list of evaluation stages, for example this specifies the filtering and
    /// indexing for various expressions.
    pub stages: Option<Vec<Ast>>,

    /// A variable to bind the index of a step to
    pub index: Option<String>,

    /// A variable to bind the context of a step to
    pub focus: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Ast {
    pub kind: AstKind,

    /// The index in the original source that introduced this node
    pub char_index: usize,

    pub keep_array: bool,
    pub cons_array: bool,
    pub keep_singleton_array: bool,

    /// Set on a step to indicate that it produces tuple bindings for things like index and focus
    /// binds, and parent resolution.
    pub tuple: bool,

    extras: Option<Box<AstExtras>>,
}

impl Default for Ast {
    fn default() -> Ast {
        Ast::new(AstKind::Empty, Default::default())
    }
}

impl Ast {
    pub fn new(kind: AstKind, char_index: usize) -> Self {
        Self {
            kind,
            char_index,
            keep_array: false,
            cons_array: false,
            keep_singleton_array: false,
            tuple: false,
            extras: None,
        }
    }

    /// Returns a mutable reference to the extras, lazily initializing if absent.
    pub fn extras_mut(&mut self) -> &mut AstExtras {
        self.extras
            .get_or_insert_with(|| Box::new(AstExtras::default()))
    }

    /// Returns a reference to the extras, if present.
    pub fn extras(&self) -> Option<&AstExtras> {
        self.extras.as_deref()
    }

    pub fn group_by(&self) -> Option<&(usize, Object)> {
        self.extras.as_ref().and_then(|e| e.group_by.as_ref())
    }

    pub fn group_by_mut(&mut self) -> &mut Option<(usize, Object)> {
        &mut self.extras_mut().group_by
    }

    pub fn predicates(&self) -> Option<&Vec<Ast>> {
        self.extras.as_ref().and_then(|e| e.predicates.as_ref())
    }

    pub fn predicates_mut(&mut self) -> &mut Option<Vec<Ast>> {
        &mut self.extras_mut().predicates
    }

    pub fn stages(&self) -> Option<&Vec<Ast>> {
        self.extras.as_ref().and_then(|e| e.stages.as_ref())
    }

    pub fn stages_mut(&mut self) -> &mut Option<Vec<Ast>> {
        &mut self.extras_mut().stages
    }

    pub fn index(&self) -> Option<&String> {
        self.extras.as_ref().and_then(|e| e.index.as_ref())
    }

    pub fn index_mut(&mut self) -> &mut Option<String> {
        &mut self.extras_mut().index
    }

    pub fn focus(&self) -> Option<&String> {
        self.extras.as_ref().and_then(|e| e.focus.as_ref())
    }

    pub fn focus_mut(&mut self) -> &mut Option<String> {
        &mut self.extras_mut().focus
    }
}
