name: Release Management

permissions:
  pull-requests: write
  contents: write

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v0.1.9
  workflow_dispatch:

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  # Step 1: Publish the release to crates.io when a new tag is pushed
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log Environment Info
        run: |
          echo "PATH: $PATH"
          echo "Current directory: $(pwd)"
          ls -la # List contents of current directory

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Verify Cargo Credentials
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "Checking Cargo credentials..."
          if [ -z "$CARGO_REGISTRY_TOKEN" ]; then
            echo "Error: CARGO_REGISTRY_TOKEN is not set."
            exit 1
          else
            echo "CARGO_REGISTRY_TOKEN is set."
          fi

      - name: Debug Cargo Config
        run: |
          cargo --version
          echo "Cargo home: $CARGO_HOME"
          echo "Cargo registry token configured."

      - name: Publish to crates.io
        run: cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: List Target Directory Contents
        run: ls -la target/package # Check if .crate files exist in package folder

      - name: Create GitHub Release
        id: gh_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}

      - name: Confirm Publish Success
        run: echo "Published to crates.io successfully."

  # Step 2: After publishing, create a new release PR to bump Cargo.toml and update changelog
  release-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    needs: publish # Ensures release PR runs only after publish job is successful
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz to open a release PR
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
