name: Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    steps:
      - name: Verify TEST_GITHUB_TOKEN and PUBLIC_PACKAGE_GITHUB_TOKEN are set
        run: |
          if [ -z "${{ secrets.TEST_GITHUB_TOKEN }}" ]; then
            echo "Error: TEST_GITHUB_TOKEN is not set or is empty."
            exit 1
          fi
          if [ -z "${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}" ]; then
            echo "Error: PUBLIC_PACKAGE_GITHUB_TOKEN is not set or is empty."
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz release
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Verify TEST_GITHUB_TOKEN and PUBLIC_PACKAGE_GITHUB_TOKEN are set
        run: |
          if [ -z "${{ secrets.TEST_GITHUB_TOKEN }}" ]; then
            echo "Error: TEST_GITHUB_TOKEN is not set or is empty."
            exit 1
          fi
          if [ -z "${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}" ]; then
            echo "Error: PUBLIC_PACKAGE_GITHUB_TOKEN is not set or is empty."
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz PR task
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
